// <auto-generated />
using System;
using KrishiClinic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KrishiClinic.API.Migrations
{
    [DbContext(typeof(KrishiClinicDbContext))]
    [Migration("20250923095950_FixPendingChanges")]
    partial class FixPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("KrishiClinic.API.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "brijmohangurjar48@gmail.com",
                            IsActive = true,
                            Name = "Brijmohan Gurjar",
                            Password = "$2a$11$rQZ8K3tXvL7hM9nP2qR1te8K5wF3sA6bC9dE1fG4hI7jK0lM3nP6q",
                            Role = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DeliveryVillage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-quality organic tomato seeds for healthy growth. Perfect for home gardening.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Tomato",
                            Price = 299m,
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Balanced NPK fertilizer for all types of crops. Promotes healthy plant growth.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Fertilizer - NPK 19:19:19",
                            Price = 450m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Pesticides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Systemic insecticide for controlling sucking pests like aphids, whiteflies, and thrips.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Bayer Crop Science - Confidor",
                            Price = 450m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "Fungicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fungicide for controlling leaf spot, rust and powdery mildew in various crops.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Syngenta - Tilt",
                            Price = 650m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Diammonium phosphate fertilizer for promoting root development and flowering.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "DAP Fertilizer - 18:46:0",
                            Price = 320m,
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High nitrogen content urea fertilizer for vegetative growth and green foliage.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Urea - 46:0:0",
                            Price = 280m,
                            StockQuantity = 120
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "Herbicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-selective herbicide for controlling weeds in agricultural fields.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Roundup - Glyphosate",
                            Price = 580m,
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium quality chilli seeds with high yield potential and disease resistance.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Chilli",
                            Price = 350m,
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Muriate of Potash for improving fruit quality and disease resistance.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "MOP Fertilizer - 0:0:60",
                            Price = 380m,
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "Insecticides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Systemic insecticide for controlling aphids, jassids, and whiteflies in cotton and vegetables.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Imidacloprid - 17.8% SL",
                            Price = 520m,
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-yielding brinjal seeds with excellent fruit quality and market demand.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Brinjal",
                            Price = 420m,
                            StockQuantity = 85
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "Fungicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contact fungicide for controlling early and late blight in potato and tomato crops.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Mancozeb - 75% WP",
                            Price = 480m,
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Single Super Phosphate for root development and early crop establishment.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "SSP Fertilizer - 0:16:0",
                            Price = 340m,
                            StockQuantity = 95
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "Herbicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Selective herbicide for controlling broadleaf weeds in wheat and rice fields.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "2,4-D Herbicide",
                            Price = 620m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium onion seeds with high bulb weight and good storage quality.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Onion",
                            Price = 380m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductId = 16,
                            Category = "Insecticides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organophosphate insecticide for controlling soil and foliar pests in various crops.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Chlorpyrifos - 20% EC",
                            Price = 580m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 17,
                            Category = "Fertilizers",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Balanced complex fertilizer for flowering and fruiting crops like tomato and brinjal.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Complex Fertilizer - 12:32:16",
                            Price = 420m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 18,
                            Category = "Fungicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Systemic fungicide for controlling sheath blight, blast and other fungal diseases.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Carbendazim - 50% WP",
                            Price = 550m,
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 19,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-yielding okra seeds with tender, long pods suitable for market and home use.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Okra",
                            Price = 320m,
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductId = 20,
                            Category = "Herbicides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Contact herbicide for controlling weeds in plantation crops and non-crop areas.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Paraquat - 24% SL",
                            Price = 680m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 21,
                            Category = "Seeds",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium cucumber seeds with high yield, disease resistance and excellent fruit quality.",
                            ImageUrl = "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Organic Seeds - Cucumber",
                            Price = 290m,
                            StockQuantity = 70
                        },
                        new
                        {
                            ProductId = 22,
                            Category = "Insecticides",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Synthetic pyrethroid insecticide for controlling lepidopteran pests in cotton and vegetables.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Lambda Cyhalothrin - 5% EC",
                            Price = 720m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 23,
                            Category = "Micronutrients",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Essential micronutrients including zinc, boron, iron, and manganese for healthy crop growth.",
                            ImageUrl = "https://images.unsplash.com/photo-1586771107445-d3ca888129ce?w=300&h=300&fit=crop",
                            IsActive = true,
                            Name = "Micronutrient Mixture",
                            Price = 890m,
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("KrishiClinic.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("OTP")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime?>("OTPExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Cart", b =>
                {
                    b.HasOne("KrishiClinic.API.Models.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KrishiClinic.API.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Order", b =>
                {
                    b.HasOne("KrishiClinic.API.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.OrderItem", b =>
                {
                    b.HasOne("KrishiClinic.API.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KrishiClinic.API.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("KrishiClinic.API.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
